# Generated by Django 4.0.3 on 2022-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KahveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Kahve')),
                ('aciklama', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('fotograf', models.ImageField(upload_to='kahveler/')),
            ],
            options={
                'verbose_name': 'Kahve',
                'verbose_name_plural': 'Kahveler',
            },
        ),
    ]
